---

# Just copy the R package installation script. This will need to be run on the VM once deployed, and after adapting the package lists according to their sources - See install_R_pkgs script

- name: find files to copy
  find:
    paths: "{{vm.ansible_dir}}/roles/r_pkgs/files/"
    patterns: "*"
  register: files_to_copy

- name: Copy the utils into /usr/local/bin
  copy:
    src: "{{ item.path }}"
    dest: /usr/local/bin/
    mode: 0775
  with_items: "{{ files_to_copy.files }}"

