---
- hosts: all
  become: true
  become_user: root
  #gather_facts: no

  vars_files:
    - vars/all.yml

  environment:
    PYTHONHTTPSVERIFY: 0

  roles:
    - vm
    - server
    - repositories
    - install-r
    - jupyterhub
    - python_pkgs
    - r_pkgs

  handlers:
    - name: Apply netplan
      ansible.builtin.command: netplan apply
