---

- name: find files to copy
  find:
    paths: "{{vm.ansible_dir}}/roles/jupyterhub/files/bin/"
    patterns: "*"
  register: files_to_copy

- name: Copy the utils into /usr/local/bin
  copy:
    src: "{{ item.path }}"
    dest: /usr/local/bin/
    mode: 0775
  with_items: "{{ files_to_copy.files }}"

- name: Generate the jupyterhub config file
  script:
    chdir: /opt/tljh/config/jupyterhub_config.d/
    cmd: "/opt/tljh/hub/bin/jupyterhub --generate-config"

- name: Set jupyterHub.bind_url
  lineinfile: 
    dest=/opt/tljh/config/jupyterhub_config.d/jupyterhub_config.py
    regexp='^.*c.JupyterHub.bind_url' 
    line="c.JupyterHub.bind_url = 'http://<<VM_NAME>>'"
    owner=root 
    group=root 
    mode=0644

- name: Set jupyterHub.hub_ip
  lineinfile: 
    dest=/opt/tljh/config/jupyterhub_config.d/jupyterhub_config.py
    regexp='^.*c\.JupyterHub.hub_ip' 
    line="c.JupyterHub.hub_ip = ''"
    owner=root 
    group=root 
    mode=0644

- name: Rename jupyterhub config file as a template
  command: mv /opt/tljh/config/jupyterhub_config.d/jupyterhub_config.py /opt/tljh/config/jupyterhub_config.d/jupyterhub_config.tpl

- name: Copy jupyterhub.service with owner and permissions
  copy:
    src: "{{vm.ansible_dir}}/roles/jupyterhub/files/systemd/jupyterhub.service"
    dest: /etc/systemd/system/jupyterhub.service
    owner: root
    group: root
    mode: 0644

- name: Restart jupyterhub application
  systemd:
    name: jupyterhub
    enabled: yes
    state: "restarted"
    daemon_reload: yes

- name: Creates an entry like "@reboot /usr/local/bin/startup"
  ansible.builtin.cron:
    name: "a job for reboot"
    special_time: reboot
    job: "/usr/local/bin/startup"
